# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_name',
            field=models.CharField(blank=True, help_text=b'Your Twitter URL', max_length=255, null=True),
        ),
    ]
