# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook_appid',
            field=models.CharField(blank=True, help_text='Your Facbook AppID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(blank=True, help_text='Your Github URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Your Instagram URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Your Linkedin URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_name',
            field=models.URLField(blank=True, help_text='Your Twitter URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube Channel URL', null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_page.html', 'Default Template'), ('pages/standard_page_full.html', 'Standard Page Full')], default='pages/standard_page.html', max_length=255),
        ),
    ]
