# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20161220_1345'),
        ('pages', '0009_auto_20161220_0853'),
    ]

    operations = [
    ]
