# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('pages', '0010_merge_20161220_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='An optional image to represent the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_name',
            field=models.CharField(blank=True, help_text='Your Twitter Username without @', max_length=255, null=True),
        ),
    ]
