# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 13:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20170105_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([(b'paragraph', wagtail.core.blocks.RichTextBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'html', wagtail.core.blocks.RawHTMLBlock())]),
        ),
    ]
