# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20170817_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='button_text',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
