# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_sitebranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardindexpage',
            name='template_string',
            field=models.CharField(choices=[(b'pages/standard_index_page.html', b'Default Template'), (b'pages/standard_index_page_grid.html', b'Grid Also In This Section')], default=b'pages/standard_index_page.html', max_length=255),
        ),
    ]
