# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20171102_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
