# Generated by Django 2.0.6 on 2018-06-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20180607_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='twitter_name',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter URL', max_length=255, null=True),
        ),
    ]
