{% raw %}---
- name: update the apt-cache
  apt: update_cache=yes cache_valid_time=3600
  become_user: root
  become: true
  tags:
     - redis

- name: install redis from via apt package
  apt: pkg=redis-server state=latest
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version >= '16' or ansible_distribution_major_version == '18')
  tags:
     - redis

- name: Ensure that redis only listens only to localhost
  lineinfile: dest=/etc/redis/redis.conf
                regexp='^#bind 127\.0\.0\.1'
                line='bind 127.0.0.1'
                state=present
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '16' or ansible_distribution_major_version == '18')
  tags:
     - redis

- name: Start the redis server xenial
  service: name=redis-server state=restarted
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '16' or ansible_distribution_major_version == '18')
  tags:
     - redis
# Ubuntu Trusty requires source install
- name: install dependencies
  apt:  pkg={{ item }} state=latest
  with_items:
    - gcc
    - make
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
     - redis

- name: Download redis tar file
  get_url: url=http://download.redis.io/redis-stable.tar.gz
           dest=/usr/local/src/redis-stable.tar.gz
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
     - redis

- name: Untar the Redis tarball
  shell: tar xf /usr/local/src/redis-stable.tar.gz -C /usr/local/src
  args:
      creates: /usr/local/src/redis-stable
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
      - redis

- name: make redis
  command: make
  become_user: root
  become: true
  args:
      chdir: /usr/local/src/redis-stable
      creates: /usr/local/src/redis-stable/src/redis-server
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
     - redis

- name: install redis
  command: make install
  become_user: root
  become: true
  args:
      chdir: /usr/local/src/redis-stable
      creates: /usr/local/bin/redis-server
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
     - redis

- name: Run the redis install script
  shell: yes '' | ./install_server.sh
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  args:
      chdir: /usr/local/src/redis-stable/utils
  tags:
     - redis

- name: Ensure that redis only listens only to localhost
  lineinfile: dest=/etc/redis/6379.conf
                regexp='^#bind 127\.0\.0\.1'
                insertafter='^#bind'
                line='bind 127.0.0.1'
                state=present
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
     - redis


- name: Restart redis
  command: service redis_6379 start
  become_user: root
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags:
    - redis{% endraw %}
