{% raw %}---
- name: ensure bitbucket.org is in known_hosts
  lineinfile:
  args:
    dest: /home/{{ deploy_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
    regexp: "^bitbucket\\.org"
  when: vcs_host == 'bitbucket.org'
  tags:
      - web
      - vcs_repo

- name: ensure github.com is known_host
  lineinfile:
  args:
    dest: /home/{{ deploy_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  when: vcs_host == 'github.com'
  tags:
      - web
      - vcs_repo

- name: Create the Sites Directory if not present 
  file: path={{ sites_dir }} owner={{ deploy_user }} state=directory
  become_user: root
  become: true
  tags:
      - web 
      - hg
      - vcs_repo

- name: clone git repo 
  git: repo={{ project_repo }} dest="{{ sites_dir }}/{{ project_name }}"
  when: vcs == 'git'
  tags:
      - web 
      - git
      - vcs_repo

- name: clone hg repo
  git: repo={{ project_repo }} dest="{{ sites_dir }}/{{ project_name }}"
  when: vcs == 'hg'
  tags:
      - web 
      - hg
      - vcs_repo {% endraw %}
