{% raw %}---
- name: initial warning 
  pause: prompt="This playbook will pause to allow you to add your authorized keys to the keystore
                 Please press [Enter] to continue"
  tags:
    - user

- name: Add the deploy user
  user: name='{{ deploy_user }}' shell=/bin/bash groups=sudo append=yes
  become: true
  tags:
    - user


- name: Ensure that sudo does not require a password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
  become: true
  tags:
    - user

- name: create the ssh dir
  file: path=/home/{{ deploy_user }}/.ssh/
        owner='{{ deploy_user }}'
        group='{{ deploy_user }}'
        state=directory
  become: true 
  tags:
    - user

- name: Copy the authorized file to the .ssh dir
  copy: src={{ keystore_path }}/authorized_keys
        dest=/home/{{ deploy_user }}/.ssh/authorized_keys 
        owner='{{ deploy_user }}'
        group='{{ deploy_user }}'
  become: true 
  tags:
    - user


- name: Create the ssh key pair for the deploy user
  user: name='{{ deploy_user }}' generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  tags:
      - user
      - sshkeys

- name: Download the deploy users public keys to your keys directory
  fetch:  src=/home/{{ deploy_user }}/.ssh/id_rsa.pub
      dest={{ keystore_path }}/{{ inventory_hostname }}-{{ deploy_user }}-deploy_keys.pub flat=yes
  tags:
    - user
    - sshkeys

- name: Prompt to upload deployment keys 
  pause: prompt="Deployment key has been downloaded to keystore. Please add to your VCS  Host
                 Please press [Enter] after you've added keys" 
  tags:
    - user{% endraw %}
