# Generated by Django 2.1.3 on 2018-11-22 16:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalleryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('feed_image', models.ForeignKey(blank=True, help_text='An optional image to represent the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Photo Gallery Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='galleryindex',
            name='images_per_page',
            field=models.IntegerField(default=20, help_text='How many images there should be on one page.', verbose_name='Images per page'),
        ),
    ]
