# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('pages', '0006_standardpage_template_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text=b'Your Facebook page URL')),
                ('instagram', models.CharField(help_text=b'Your Instagram username, without the @', max_length=255)),
                ('twitter_name', models.CharField(help_text=b'Your Twitter username, without the @', max_length=255)),
                ('youtube', models.URLField(help_text=b'Your YouTube channel or user account URL')),
                ('facebook_appid', models.CharField(help_text=b'Your Facbook AppID', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
