# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20160816_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
