# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactpage_telephone_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
