# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('contact', '0007_contactpage_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
