{% raw %}---
- name: Ensure that nginx is installed
  apt: name=nginx state=latest update_cache=yes cache_valid_time=36000
  become_user: root
  become: yes
  tags:
      - nginx 

- name: stop nginx service 
  service: name=nginx state=stopped
  become: yes
  become_user: root
  tags:
      - nginx 

- name: Check the certificate is there
  become: yes
  become_user: root
  stat:
    path: "/etc/letsencrypt/live/{{ django_env.HOST_NAME }}/fullchain.pem"
  when: use_ssl|bool 
  register: cert_stat
  tags:
      - ssl
      - nginx 

- name:  nginx config without SSL
  become: yes
  become_user: root
  template: src=nginx.j2
            dest=/etc/nginx/sites-available/{{ project_name }}
            backup=yes
  when: not use_ssl|bool
  tags:
      - no_ssl
      - nginx


- name: nginx config with SSL 
  become: yes
  become_user: root
  template: src=nginx_ssl.j2
            dest=/etc/nginx/sites-available/{{ project_name }}
            backup=yes
  when: use_ssl|bool and cert_stat.stat.exists
  tags:
       - ssl
       - nginx

- name: change the cli.ini to support webroot
  become: yes
  become_user: root
  template: src=le-cli-webroot.j2
            dest=/etc/letsencrypt/cli.ini
            backup=yes
  when: use_ssl|bool and cert_stat.stat.exists
  tags:
       - ssl
       - nginx 


- name: Add the renewal cronjob to the system
  become: yes
  become_user: root
  cron: name="LE certificate renewal" minute="30" hour="2,7"  
        job="/usr/bin/letsencrypt renew >> /var/log/le-renewal.log"
  when: use_ssl|bool and cert_stat.stat.exists
  tags:
    - ssl
    - nginx 

- name: Ensure that the default site is disabled
  become: yes
  become_user: root
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default
  tags:
      - nginx

- name: Ensure the site will start in maint mode
  become: yes
  become_user: root
  template: src=offline.j2
            dest='/usr/share/nginx/html/{{ project_name }}_offline.html'
  tags:
     - nginx

- name: enable and restart the site 
  become: yes
  become_user: root
  file: src=/etc/nginx/sites-available/{{ project_name }} 
      dest=/etc/nginx/sites-enabled/{{ project_name }} state=link
  notify: restart nginx
  tags:
     - nginx{% endraw %}
