# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170529_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'markdown', wagtailmarkdown.fields.MarkdownBlock(icon=b'code')), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock())]),
        ),
    ]
