# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160721_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='link_demo',
        ),
    ]
