# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160722_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productpage',
            name='link_demo',
            field=models.URLField(blank=True, verbose_name=b'Demo link'),
        ),
    ]
