# Generated by Django 2.2.1 on 2019-07-18 14:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_nationality',
            field=django_countries.fields.CountryField(blank=True, default='TT', max_length=2, verbose_name='Country of Nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=django_countries.fields.CountryField(default='TT', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Job Title or Occupation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Organisation'),
        ),
    ]
