# Generated by Django 3.2.8 on 2021-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190718_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_of_residence',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
