{% raw %}---
- name: update the apt-cache
  apt: update_cache=yes cache_valid_time=3600
  become_user: root
  become: true
  tags:
     - redis

- name: install dependencies
  apt:  pkg={{ item }} state=latest
  with_items:
    - gcc
    - make
  become_user: root
  become: true 
  tags:
     - redis

- name: Download redis tar file
  get_url: url=http://download.redis.io/redis-stable.tar.gz
           dest=/usr/local/src/redis-stable.tar.gz
  become_user: root
  become: true 
  tags:
     - redis

- name: Un tar the Redis tarball
  shell: tar xf /usr/local/src/redis-stable.tar.gz -C /usr/local/src
  args:
      creates: /usr/local/src/redis-stable
  become_user: root
  become: true 
  tags:
      - redis

- name: make redis
  command: make
  become_user: root
  become: true 
  args: 
      chdir: /usr/local/src/redis-stable
      creates: /usr/local/src/redis-stable/src/redis-server
  tags:
     - redis

- name: install redis
  command: make install
  become_user: root
  become: true 
  args:
      chdir: /usr/local/src/redis-stable
      creates: /usr/local/bin/redis-server
  tags:
     - redis

- name: Run the redis install script
  shell: yes '' | ./install_server.sh
  become_user: root
  become: true 
  args:
      chdir: /usr/local/src/redis-stable/utils
  tags:
     - redis

- name: Ensure that redis only listens only to localhost
  lineinfile: dest=/etc/redis/6379.conf 
                regexp='^#bind 127\.0\.0\.1'
                insertafter='^#bind'
                line='bind 127.0.0.1'
                state=present
  become_user: root
  become: true 
  tags:
     - redis 

- name: Start the redis server
  command: service redis_6379 start
  become_user: root
  become: true 
  tags:
     - redis
     - redisdebug 

- name: Restart redis 
  command: update-rc.d redis_6379 defaults
  command: service redis_6379 start
  become_user: root
  become: true 
  tags:
    - redis{% endraw %}
