---
- name: Authorized hosts for bitbucket
  shell: ssh-keyscan -H bitbucket.org >> /home/{{ deploy_user }}/.ssh/known_hosts
  args:
      creates: /home/{{ deploy_user }}/.ssh/known_hosts
  sudo: no
  tags:
      - hg
      - test

- name: Create the Sites Directory if not present 
  file: path={{ sites_dir }} owner={{ deploy_user }} state=directory
  tags:
      - web 
      - hg
        
- name: clone repo from bitbucket
  command: hg clone {{ project_repo }} 
  sudo: no
  args:
      chdir: "{{ sites_dir }}"
      creates: "{{ sites_dir }}/{{ project_name }}"
  tags:
      - web 
      - hg
