# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20151021_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
