# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='link_demo',
            field=models.URLField(blank=True, verbose_name=b'Demo link'),
        ),
    ]
