# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productpage_link_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
