{% raw %}---
- name: update the apt-cache
  apt: update_cache=yes  cache_valid_time=36000
  become: yes
  tags:
      - pg_install

- name: Install PostgreSQL
  become: yes
  apt:
      pkg:
        - postgresql-12-postgis-3
        - libpq-dev
        - postgresql-client-common
        - python3-psycopg2

  tags:
      - pg_install

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes
  become: yes
  tags:
      - pg_install

- name: Create the database for the project
  become_user: postgres
  become: true
  postgresql_db: name={{ django_env.DB_NAME }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present
  tags:
      - pg_install
      - pg_config

- name: Ensure user has access to the database
  become_user: postgres
  become: true
  postgresql_user: db={{ django_env.DB_NAME }}
                   name={{ django_env.DB_USER }}
                   password={{ django_env.DB_PASSWD }}
                   encrypted=yes
                   priv=ALL
                   state=present
  tags:
      - pg_install
      - pgconfig

- name: Ensure user does not have unnecessary privileges
  become_user: postgres
  become: true
  postgresql_user: name={{ django_env.DB_USER }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present
  tags:
      - pg_install
      - pg_config{% endraw %}
